services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: production
    container_name: menyalo
    env_file:
      - .env.docker
    ports:
      - '5001:5000'
    volumes:
      - ./:/usr/src/app/
      - node_modules:/app/node_modules
    command: >
      sh -c "
      npm run db:migrate && 
      npm run db:seed && 
      npm run dev
      "
    networks:
      - menyalo-network
volumes:
  node_modules:

networks:
  menyalo-network:
    driver: bridge